name: Restrict Direct Push


on:
  push:
    branches:
      - main    #protect the main branch

jobs:
  prevent-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Block Direct Push
        run: |
         echo "Direct Push to Main is not allowed use a Pull Request"
         exit 1